# Default values for mychart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: "containous/whoami"
  tag: latest

resources:
  requests:
    memory: "100Mi"
    cpu: "50m"
  limits:
    memory: "200Mi"
    cpu: "200m"

nodeSelector: {}

tolerations: []

affinity: {}

healthEndpoint: /

path: /who/

host: k3s.rpy3.com

env: testing

port: 80

traefikMiddleware: false



