apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ include "mychart.fullname" . }}
  annotations:
    kubernetes.io/ingress.class: traefik
    {{ if .Values.traefikMiddleware}}
    ingress.kubernetes.io/auth-type: forward
    ingress.kubernetes.io/auth-url: http://traefik-forward-auth:4181
    ingress.kubernetes.io/auth-response-headers: X-Forwarded-User
    {{ end }}
spec:
  rules:
  - host: {{ .Values.host }}
    http:
      paths:
      - backend:
          serviceName: {{ include "mychart.fullname" . }}
          servicePort: {{ .Values.port }}
        path: {{ .Values.path }}