apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ include "mychart.fullname" . }}
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
  - host: {{ .Values.host }}
    http:
      paths:
      - backend:
          serviceName: {{ include "mychart.fullname" . }}
          servicePort: {{ .Values.port }}
        path: {{ .Values.path }}